name: run_all_tests

on: [push, pull_request, workflow_dispatch]

jobs:
  RunAllTests:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - name: run_all_tests
        run: |
          pip3 install -r requirements.txt
          pip3 install -r test-requirements.txt
          python3 -m pytest